/**
 * Phase 1 — parser proof.
 *
 * Clones abapGit (shallow) into .seed-cache/, parses every .abap file with
 * @abaplint/core via lib/parser/extract.ts, and reports:
 *   - total files, parsed OK, failed (per-file reason), success rate
 *   - a printed extraction sample (objects, calls, table accesses)
 *
 * Gate: success rate >= 80%; failure summary written to docs/parse-failures.md.
 */
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { extractWorkspace, type ParseInput } from "../lib/parser/extract";

const REPO_URL = "https://github.com/abapGit/abapGit";
const CACHE_DIR = join(process.cwd(), ".seed-cache");
const REPO_DIR = join(CACHE_DIR, "abapGit");

function listAbapFiles(dir: string): string[] {
  const out = execFileSync("find", [dir, "-name", "*.abap", "-type", "f"], {
    encoding: "utf8",
  });
  return out.split("\n").filter(Boolean).sort();
}

function main() {
  if (!existsSync(REPO_DIR)) {
    mkdirSync(CACHE_DIR, { recursive: true });
    console.log(`cloning ${REPO_URL} (shallow) ...`);
    execFileSync("git", ["clone", "--depth", "1", REPO_URL, REPO_DIR], {
      stdio: "inherit",
    });
  }

  const paths = listAbapFiles(REPO_DIR);
  const inputs: ParseInput[] = paths.map((p) => ({
    path: relative(REPO_DIR, p),
    contents: readFileSync(p, "utf8"),
  }));
  console.log(`parsing ${inputs.length} .abap files with @abaplint/core ...`);

  const started = Date.now();
  const result = extractWorkspace(inputs);
  const elapsed = ((Date.now() - started) / 1000).toFixed(1);

  // ---- per-file status (a file fails if its object failed because of it) ----
  const failedFiles = new Map<string, string>();
  for (const obj of result.objects) {
    for (const err of obj.parseErrors) {
      if (!failedFiles.has(err.file)) {
        failedFiles.set(err.file, `line ${err.line}: unparsed statement: ${err.snippet}`);
      }
    }
  }
  for (const f of result.unattachedFiles) failedFiles.set(f.path, f.reason);

  const total = inputs.length;
  const failed = failedFiles.size;
  const ok = total - failed;
  const rate = (100 * ok) / total;

  console.log(`\n== Parse summary (${elapsed}s) ==`);
  console.log(`total .abap files : ${total}`);
  console.log(`parsed OK         : ${ok}`);
  console.log(`failed            : ${failed}`);
  console.log(`success rate      : ${rate.toFixed(2)}%`);
  console.log(
    `objects           : ${result.totals.objects} (${result.totals.objectsOk} ok / ${result.totals.objectsFailed} with failures)`
  );

  // ---- docs/parse-failures.md ----
  const docsDir = join(process.cwd(), "docs");
  mkdirSync(docsDir, { recursive: true });
  const failureLines = [...failedFiles.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([file, reason]) => `| \`${file}\` | ${reason.replace(/\|/g, "\\|")} |`);
  writeFileSync(
    join(docsDir, "parse-failures.md"),
    `# Parse failures — abapGit repo (Phase 1 proof)

Generated by \`npm run parse-proof\` on ${new Date().toISOString().slice(0, 10)}.
Parser: @abaplint/core. Failures never block seeding: failed objects are stored
with \`parse_status='failed'\` plus raw source.

- Total \`.abap\` files: **${total}**
- Parsed OK: **${ok}**
- Failed: **${failed}**
- Success rate: **${rate.toFixed(2)}%**

${failed === 0 ? "No failures." : `| File | Reason |\n| --- | --- |\n${failureLines.join("\n")}`}
`
  );
  console.log(`failure summary written to docs/parse-failures.md`);

  // ---- extraction proof on a handful of objects ----
  const interesting = result.objects
    .filter((o) => o.parseStatus === "ok" && o.tableAccesses.length > 0 && o.calls.some((c) => c.kind === "function"))
    .slice(0, 3);
  const withPerform = result.objects.find((o) => o.calls.some((c) => c.kind === "perform"));
  const sample = [...interesting, ...(withPerform ? [withPerform] : [])].slice(0, 4);

  console.log(`\n== Extraction sample (${sample.length} objects) ==`);
  for (const obj of sample) {
    console.log(`\n${obj.type} ${obj.name}  (${obj.files.join(", ")})`);
    const funcs = obj.calls.filter((c) => c.kind === "function").slice(0, 3);
    const performs = obj.calls.filter((c) => c.kind === "perform").slice(0, 3);
    const classes = obj.calls.filter((c) => c.kind === "class").slice(0, 3);
    for (const c of [...funcs, ...performs, ...classes]) {
      console.log(`  call [${c.kind}] ${c.target}  (${c.file}:${c.line})`);
    }
    for (const t of obj.tableAccesses.slice(0, 3)) {
      console.log(`  table [${t.op}] ${t.table}${t.dynamic ? " (dynamic)" : ""}  (${t.file}:${t.line})  evidence: ${t.evidence.slice(0, 80)}`);
    }
  }

  const gate = rate >= 80;
  console.log(`\nGATE (success rate >= 80%): ${gate ? "PASS" : "FAIL"}`);
  process.exit(gate ? 0 : 1);
}

main();
