#!/usr/bin/env python3
"""
CPI iFlow Packager — create, validate, and extract SAP CPI integration flow ZIP files.

CPI iFlow ZIP structure:
  META-INF/MANIFEST.MF              — Bundle metadata
  src/main/resources/flow.xml        — Main integration flow descriptor
  src/main/resources/script/*.groovy  — Groovy scripts
  src/main/resources/mapping/*.xslt   — XSLT mappings
  src/main/resources/mapping/*.mmap   — Message mappings
  src/main/resources/resources/*     — EDI schemas, WSDLs, etc.
  src/main/resources/value-mapping/*.vmap  — Value mappings
  src/main/resources/parameters.prop — Externalized parameters

Usage:
  python scripts/cpi_iflow_packager.py create --name <id> --flow <file>
        [--scripts <files>] [--mappings <files>] [--resources <dir>]
        [--parameters <file>] [--output <file.zip>]

  python scripts/cpi_iflow_packager.py validate --input <file.zip>

  python scripts/cpi_iflow_packager.py extract --input <file.zip> --output <dir>

  python scripts/cpi_iflow_packager.py list --input <file.zip>

  python scripts/cpi_iflow_packager.py template --name <id> --output <file.zip>
    Generate a starter iFlow ZIP with minimal flow.xml + example Groovy script.
"""

import argparse
import os
import sys
import json
import zipfile
import tempfile
import shutil
from datetime import datetime, timezone
from pathlib import Path
from xml.dom import minidom
from xml.etree import ElementTree as ET


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

MANIFEST_TEMPLATE = """Manifest-Version: 1.0
Created-By: SAP Router Orchestrator CPI Packager
Bundle-SymbolicName: {name}
Bundle-Version: 1.0.0
Bundle-Name: {name}
Bundle-Vendor: Generated by sap-router-orchestrator
Created-Date: {date}
"""

FLOW_TEMPLATE = """<?xml version="1.0" encoding="UTF-8"?>
<IntegrationFlow
  xmlns="http://xmlns.sap.com/CPI/IntegrationFlow"
  id="{name}"
  version="1.0">

  <Sender id="sender_1" type="HTTPS" direction="Inbound">
    <Address>/api/{name}</Address>
    <Authentication>Basic</Authentication>
    <CSRFProtected>true</CSRFProtected>
  </Sender>

  <IntegrationProcess id="process_1" name="Process Request">

    <ContentModifier id="cm_headers" name="Set Request Headers">
      <Header name="Content-Type">application/json</Header>
      <Property name="MessageID" source="header" sourceField="SAP_MessageProcessingLogID"/>
      <Property name="Timestamp" value="${{date:now:yyyy-MM-dd'T'HH:mm:ss}}"/>
    </ContentModifier>

    <GroovyScript id="script_transform" name="Transform Payload"
                  scriptPath="script/transform.groovy"/>

    <RequestReply id="rr_backend" name="Call Backend">
      <Receiver ref="receiver_1"/>
      <Timeout>60000</Timeout>
    </RequestReply>

    <GroovyScript id="script_response" name="Format Response"
                  scriptPath="script/format-response.groovy"/>

  </IntegrationProcess>

  <Receiver id="receiver_1" type="ODataV2" direction="Outbound">
    <Address>${{destination.S4HANA}}/sap/opu/odata/sap/Z_SERVICE_SRV</Address>
    <Authentication>Basic</Authentication>
  </Receiver>

</IntegrationFlow>
"""

GROOVY_TRANSFORM_TEMPLATE = """import com.sap.gateway.ip.core.customdev.util.Message
import groovy.json.JsonSlurper
import groovy.json.JsonOutput

/**
 * Transform incoming payload for backend call.
 * Template generated by SAP Router Orchestrator CPI Packager.
 */
def Message processData(Message message) {
    def body = message.getBody(java.lang.String) as String

    // Parse incoming JSON
    def input = new JsonSlurper().parseText(body)

    // Transform to backend format
    def output = [
        header: [
            messageId: message.getProperties().get("MessageID"),
            timestamp: new Date().format("yyyy-MM-dd'T'HH:mm:ss.SSSZ")
        ],
        payload: input
    ]

    message.setBody(JsonOutput.toJson(output))
    message.setHeader("Content-Type", "application/json")
    return message
}
"""

GROOVY_RESPONSE_TEMPLATE = """import com.sap.gateway.ip.core.customdev.util.Message
import groovy.json.JsonSlurper
import groovy.json.JsonOutput

/**
 * Format backend response for client.
 * Template generated by SAP Router Orchestrator CPI Packager.
 */
def Message processData(Message message) {
    def body = message.getBody(java.lang.String) as String

    // Parse backend response
    def backend = new JsonSlurper().parseText(body)

    // Build client response
    def response = [
        status: "SUCCESS",
        message: "Request processed",
        data: backend?.d?.results ?: backend
    ]

    message.setBody(JsonOutput.toJson(response))
    return message
}
"""

PARAMETERS_TEMPLATE = """# CPI Externalized Parameters
# Generated by SAP Router Orchestrator CPI Packager
S4HANA=MY_S4HANA_DESTINATION
TENANT=my-tenant
LOG_LEVEL=INFO
MAX_RETRIES=3
RETRY_DELAY_MS=5000
"""

VALID_EXTENSIONS = {
    ".groovy": "script/",
    ".xslt": "mapping/",
    ".mmap": "mapping/",
    ".xsd": "resources/",
    ".wsdl": "resources/",
    ".vmap": "value-mapping/",
    ".prop": ".",
    ".xml": ".",
}

REQUIRED_FILES = [
    "META-INF/MANIFEST.MF",
    "src/main/resources/flow.xml",
]


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------

def cmd_create(args):
    """Create an iFlow ZIP from individual source files."""
    name = args.name
    output = args.output or f"{name}.zip"
    base = Path("src/main/resources")

    with zipfile.ZipFile(output, "w", zipfile.ZIP_DEFLATED) as zf:
        # 1. MANIFEST.MF
        manifest = MANIFEST_TEMPLATE.format(
            name=name,
            date=datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        )
        zf.writestr("META-INF/MANIFEST.MF", manifest)

        # 2. flow.xml
        if args.flow:
            zf.write(args.flow, str(base / "flow.xml"))
        else:
            zf.writestr(str(base / "flow.xml"), FLOW_TEMPLATE.format(name=name))

        # 3. Groovy scripts
        for script in (args.scripts or []):
            dest = base / "script" / os.path.basename(script)
            zf.write(script, str(dest))

        # 4. Mappings (XSLT, MMap)
        for mapping in (args.mappings or []):
            ext = os.path.splitext(mapping)[1]
            subdir = "mapping" if ext in (".xslt", ".mmap") else "resources"
            dest = base / subdir / os.path.basename(mapping)
            zf.write(mapping, str(dest))

        # 5. Resources directory
        if args.resources:
            res_path = Path(args.resources)
            for f in res_path.rglob("*"):
                if f.is_file():
                    rel = f.relative_to(res_path)
                    zf.write(str(f), str(base / "resources" / rel))

        # 6. Value mappings
        for vmap in (args.vmaps or []):
            dest = base / "value-mapping" / os.path.basename(vmap)
            zf.write(vmap, str(dest))

        # 7. Parameters
        if args.parameters:
            zf.write(args.parameters, str(base / "parameters.prop"))

        # 8. Security artifacts
        for sec in (args.security or []):
            dest = base / "security" / os.path.basename(sec)
            zf.write(sec, str(dest))

    size = os.path.getsize(output)
    print(f"Created iFlow ZIP: {output} ({size:,} bytes)")
    return 0


def cmd_template(args):
    """Generate a starter iFlow ZIP with example Groovy scripts."""
    name = args.name
    output = args.output or f"{name}-template.zip"
    base = Path("src/main/resources")

    with zipfile.ZipFile(output, "w", zipfile.ZIP_DEFLATED) as zf:
        # MANIFEST.MF
        manifest = MANIFEST_TEMPLATE.format(
            name=name, date=datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        )
        zf.writestr("META-INF/MANIFEST.MF", manifest)

        # flow.xml
        zf.writestr(str(base / "flow.xml"), FLOW_TEMPLATE.format(name=name))

        # Example Groovy scripts
        zf.writestr(str(base / "script/transform.groovy"), GROOVY_TRANSFORM_TEMPLATE)
        zf.writestr(str(base / "script/format-response.groovy"), GROOVY_RESPONSE_TEMPLATE)

        # Example parameters
        zf.writestr(str(base / "parameters.prop"), PARAMETERS_TEMPLATE)

    size = os.path.getsize(output)
    print(f"Created iFlow template: {output} ({size:,} bytes)")
    print(f"  Contents:")
    with zipfile.ZipFile(output, "r") as zf:
        for info in zf.infolist():
            print(f"    {info.filename} ({info.file_size:,} bytes)")
    return 0


def cmd_validate(args):
    """Validate iFlow ZIP structure."""
    input_path = Path(args.input)
    if not input_path.exists():
        print(f"ERROR: {input_path} not found", file=sys.stderr)
        return 1

    if not zipfile.is_zipfile(input_path):
        print(f"ERROR: {input_path} is not a valid ZIP file", file=sys.stderr)
        return 1

    errors = []
    warnings = []

    with zipfile.ZipFile(input_path, "r") as zf:
        names = set(zf.namelist())

        # Check required files
        for required in REQUIRED_FILES:
            if required not in names:
                errors.append(f"Missing required file: {required}")

        # Check MANIFEST.MF content
        if "META-INF/MANIFEST.MF" in names:
            manifest_content = zf.read("META-INF/MANIFEST.MF").decode("utf-8")
            if "Bundle-SymbolicName:" not in manifest_content:
                errors.append("MANIFEST.MF: missing Bundle-SymbolicName")
            if "Bundle-Version:" not in manifest_content:
                warnings.append("MANIFEST.MF: missing Bundle-Version")

        # Check flow.xml is valid XML
        if "src/main/resources/flow.xml" in names:
            try:
                flow_content = zf.read("src/main/resources/flow.xml")
                ET.fromstring(flow_content)
            except ET.ParseError as e:
                errors.append(f"flow.xml: invalid XML — {e}")

        # Validate Groovy scripts have .groovy extension
        for name in names:
            if "script/" in name and not name.endswith(".groovy"):
                warnings.append(f"Script without .groovy extension: {name}")
            if "mapping/" in name:
                ext = os.path.splitext(name)[1]
                if ext not in (".xslt", ".mmap", ""):
                    warnings.append(f"Unrecognized mapping extension: {name}")

        # Check for empty files
        for info in zf.infolist():
            if info.file_size == 0:
                warnings.append(f"Empty file: {info.filename}")

    # Print report
    print(f"iFlow ZIP validation: {input_path}")
    print(f"  Files: {len(names)}")
    print(f"  Required OK: {sum(1 for r in REQUIRED_FILES if r in names)}/{len(REQUIRED_FILES)}")

    if errors:
        print(f"\n  ERRORS ({len(errors)}):")
        for e in errors:
            print(f"    [ERR] {e}")
    if warnings:
        print(f"\n  WARNINGS ({len(warnings)}):")
        for w in warnings:
            print(f"    [WARN] {w}")

    if not errors:
        print(f"\n  PASS: iFlow ZIP is VALID")
        return 0
    else:
        print(f"\n  FAIL: iFlow ZIP has {len(errors)} error(s)")
        return 1


def cmd_extract(args):
    """Extract iFlow ZIP to directory (path-traversal safe)."""
    input_path = Path(args.input)
    output_dir = Path(args.output).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    with zipfile.ZipFile(input_path, "r") as zf:
        for info in zf.infolist():
            # Prevent zip-slip path traversal
            member_path = os.path.normpath(output_dir / info.filename)
            if not str(member_path).startswith(str(output_dir)):
                print(f"WARNING: Skipping suspicious path: {info.filename}", file=sys.stderr)
                continue
            zf.extract(info, output_dir)

    print(f"Extracted {input_path} -> {output_dir}")
    print(f"  Files extracted: {len(zf.namelist())}")
    return 0


def cmd_list(args):
    """List contents of iFlow ZIP."""
    input_path = Path(args.input)

    with zipfile.ZipFile(input_path, "r") as zf:
        print(f"iFlow ZIP: {input_path}")
        print(f"  Total files: {len(zf.infolist())}")
        print(f"  Total size:  {sum(i.file_size for i in zf.infolist()):,} bytes")
        print()

        # Group by directory
        dirs = {}
        for info in zf.infolist():
            d = os.path.dirname(info.filename) or "/"
            dirs.setdefault(d, []).append(info)

        for d, files in sorted(dirs.items()):
            print(f"  {d}/")
            for f in files:
                print(f"    {os.path.basename(f.filename):40s} {f.file_size:>8,} bytes")
    return 0


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="CPI iFlow Packager — create, validate, extract SAP CPI iFlow ZIPs"
    )
    sub = parser.add_subparsers(dest="command", required=True)

    # create
    c = sub.add_parser("create", help="Create iFlow ZIP from source files")
    c.add_argument("--name", "-n", required=True, help="iFlow name (Bundle-SymbolicName)")
    c.add_argument("--flow", "-f", help="flow.xml file path")
    c.add_argument("--scripts", nargs="*", help="Groovy script files")
    c.add_argument("--mappings", nargs="*", help="XSLT/MMap mapping files")
    c.add_argument("--resources", help="Resources directory (EDI schemas, WSDLs)")
    c.add_argument("--vmaps", nargs="*", help="Value mapping .vmap files")
    c.add_argument("--parameters", help="parameters.prop file")
    c.add_argument("--security", nargs="*", help="Security artifact files")
    c.add_argument("--output", "-o", help="Output ZIP path (default: <name>.zip)")

    # template
    t = sub.add_parser("template", help="Generate starter iFlow ZIP template")
    t.add_argument("--name", "-n", required=True, help="iFlow name")
    t.add_argument("--output", "-o", help="Output ZIP path")

    # validate
    v = sub.add_parser("validate", help="Validate iFlow ZIP structure")
    v.add_argument("--input", "-i", required=True, help="iFlow ZIP to validate")

    # extract
    e = sub.add_parser("extract", help="Extract iFlow ZIP to directory")
    e.add_argument("--input", "-i", required=True, help="iFlow ZIP file")
    e.add_argument("--output", "-o", required=True, help="Output directory")

    # list
    l = sub.add_parser("list", help="List contents of iFlow ZIP")
    l.add_argument("--input", "-i", required=True, help="iFlow ZIP file")

    args = parser.parse_args()

    dispatch = {
        "create":   lambda: cmd_create(args),
        "template": lambda: cmd_template(args),
        "validate": lambda: cmd_validate(args),
        "extract":  lambda: cmd_extract(args),
        "list":     lambda: cmd_list(args),
    }

    return dispatch[args.command]()


if __name__ == "__main__":
    sys.exit(main())
